-- Réactions rapides sur une critique d'ami (retour utilisateur) — un petit
-- palier d'engagement entre "rien" et "écrire un commentaire" : un emoji
-- posé sur le commentaire d'un ami (film_comments, migrations/030), pas
-- sur le film lui-même (déjà couvert par film_likes). Portée volontairement
-- limitée à film_comments — "une critique" désigne un avis écrit sur un
-- film, pas group_proposal_comments (discussion d'une proposition de
-- groupe, un contexte différent).
--
-- Plusieurs emojis DIFFÉRENTS par personne sur le même commentaire
-- (contrainte unique à 3 colonnes) — pas qu'une seule réaction au total,
-- rien n'empêche d'apprécier à la fois avec 👍 et 😂.
create table public.comment_reactions (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.film_comments(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  unique (comment_id, user_id, emoji)
);

alter table public.comment_reactions enable row level security;

-- Visible à qui peut déjà voir le commentaire réagi — pas à qui peut voir
-- l'AUTEUR DE LA RÉACTION (souvent la même personne que soi, sans intérêt),
-- d'où la jointure vers film_comments pour retrouver le bon user_id à
-- passer à are_friends() (migrations/030).
create policy "Users can view reactions on visible comments"
  on public.comment_reactions for select
  using (
    exists (
      select 1 from public.film_comments fc
      where fc.id = comment_id and public.are_friends(auth.uid(), fc.user_id)
    )
  );

create policy "Users can react as themselves"
  on public.comment_reactions for insert
  with check (auth.uid() = user_id);

create policy "Users can remove their own reaction"
  on public.comment_reactions for delete
  using (auth.uid() = user_id);
